Update patch set 3
Patch Set 3:

> Patch Set 2:
> Thanks for your comments. I modified the error message to 
> ```
> fmt.Errorf("%q does not look like a githook script. Do you have permission to access: %q?", downloadPath, hookPath)
> ```
> 
> Does that look OK?

Definitely a great step in the right direction! Might I suggest this minor change?

"%q does not look like a githook script; check your access to %q"

This has the nice property of not assuming anything about the structure of the sentence that will be made when the error is output. For example:

if err := f(); err != nil {
    fmt.Printf("Error: f() returned %s, please try again.", err)
}

With the additional sentence and ending punctuation, this results in a weird UX for the person ultimately reading the error:

Error: f() returned: "foo" does not look like a githook script. Do you have permission to access: "bar"?, please try again.

versus

Error: f() returned: "foo" does not look like a githook script; check your access to "bar", please try again.

Patch-set: 3
Reviewer: Gerrit User 30867 <30867@ccdefb6c-23ea-33ff-848c-339fc6ca2269>