Update patch set 3
Patch Set 3:

There is one issue with Patch Set 3. 

Assuming the content of .jiri_manifest is:


<manifest>
    <imports>
       <import manifest="build/build" name="integration" 
   remote="https://fuchsia.googlesource.com/integration"/>
     </imports>
</manifest>


and the content of integration/build/minimal is:

<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <projects>
    <project name="build"
             path="build"
             remote="https://fuchsia.googlesource.com/build"
             gerrithost="https://fuchsia-review.googlesource.com"
             revision="4ffa1c957c2367e8ebeadc8a578853007fba648b"/>
  </projects>
  <hooks>
    <hook name="symlink-.gn"
          project="build"
          action="dot_gn_symlink.sh"/>
  </hooks>
</manifest>

After performing 'jiri update', modify the content of integration/build/minimal to (Or any commits that is not landed yet):

<manifest>
  <projects>
    <project name="build"
             path="build"
             remote="https://fuchsia.googlesource.com/build"
             remotebranch="refs/changes/00/219700/1"
             revision="75e0bf8927b221a2430412016f646d5ecfb3e383"
             gerrithost="https://fuchsia-review.googlesource.com"
             />
  </projects>
  <hooks>
    <hook name="symlink-.gn"
          project="build"
          action="dot_gn_symlink.sh"/>
  </hooks>
</manifest>

Perform 'jiri update' again. It will fail with following messages:


ERROR: For project "build", not able to checkout latest, error: 'git checkout --detach 75e0bf8927b221a2430412016f646d5ecfb3e383' failed:
fatal: reference is not a tree: 75e0bf8927b221a2430412016f646d5ecfb3e383

command fail error: exit status 128
Please checkout manually use: 'git -C "build" checkout --detach 75e0bf8927b221a2430412016f646d5ecfb3e383'


When try this test with Patch Set 1, everything works fine.


The reason behind this is probably when changing the manifest of an existing (and cloned) project and performing 'jiri update', the 'checkoutProject' function in operations.go will not be invoked. Instead, 'func (op updateOperation) Run(jirix *jiri.X) error' will be invoked for this task. So the 'fetchRefspec' will not be invoked, causing the error. If in this test, the 'project' build was not cloned to local yet, 'jiri update' will not report an error.

I don't know if the test I run above is a legit use case in production. If so, I think we should use the Patch Set 1. Though 'checkoutHeadRevision' does not look like right place to add this feature, modifying Patch Set 3 to add another call to 'fetchRefspec' in 'syncProjectMaster' function in 'project.go' does not look like a clean way either. IMO, ideally, this 'fetchRefspec' should be done after jiri parsed manifest file when it begins to cache remote git repos to local, but it seems that there is no clean(and easy) way to patch it right now. We can revisit this problem and refactor this part later.

Patch-set: 3
Reviewer: Gerrit User 12756 <12756@ccdefb6c-23ea-33ff-848c-339fc6ca2269>