Update patch set 7
Patch Set 7:

> Patch Set 7:
> 
> > Patch Set 7:
> > 
> > (1 comment)
> 
> Hm, I had assumed that this was in a main package somewhere, but after looking at the package's implementation, I wonder whether it's possible to just import the ensure package and call ParseVersionsFile directly rather than to duplicate the functionality here.

I tried. Including "go.chromium.org/luci/cipd/client/cipd/ensure" requires protobuf3:

➜  go go build -o bin/jiri fuchsia.googlesource.com/jiri/cmd/jiri
# go.chromium.org/luci/grpc/discovery
../../../go/src/go.chromium.org/luci/grpc/discovery/service.pb.go:26:11: undefined: proto.ProtoPackageIsVersion3
➜  go 

I would prefer not to complicate the building process of jiri just for versionFile parsing.

Patch-set: 7
Reviewer: Gerrit User 12756 <12756@ccdefb6c-23ea-33ff-848c-339fc6ca2269>